Feb20-exception,assert.py